/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Iron Minecart2 (https://sketchfab.com/iron_minecart2)
license: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
source: https://sketchfab.com/3d-models/ferrari-348-tb-low-poly-54bb2829f76d4320b87bbcd667a28bd3
title: Ferrari 348 TB Low Poly
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { animated } from '@react-spring/three'

export default function Model(props) {
  //const camera = useThree(state => state.camera)

  const group = useRef();
  /**
   * use it for page transitions to rotate car
   */
  /* const { spring } = useSpring({ 
    spring: scale,
  }) */
  //const rotation = spring.to([0, 1], [0, Math.PI/2])

  const { nodes, materials, animations } = useGLTF("/scene.glb");
  const { actions } = useAnimations(animations, group);

  const handleClick = () => {
    actions.Headlights.stop()
    actions.Headlights.play()
  }

  useEffect(() => {
    actions.Headlights.setLoop(1, 1)
    actions.Headlights.play()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  
  return (
    <animated.group 
      /* scale={scale.scale} */
      ref={group} 
      {...props} 
      dispose={null}
      >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <group
            name="c13ee17b1e894681ade7508c5e3ab460fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Headlights"
                  position={[-113.89, 41.32, 0]}
                  rotation={[-Math.PI / 2, -0.49, 0]}
                  scale={100}
                  onClick={handleClick}
                >
                  <mesh
                    name="Headlights_Material001_0"
                    geometry={nodes.Headlights_Material001_0.geometry}
                    material={nodes.Headlights_Material001_0.material}
                  />
                  <mesh
                    name="Headlights_Material003_0"
                    geometry={nodes.Headlights_Material003_0.geometry}
                    material={nodes.Headlights_Material003_0.material}
                  />
                </group>
                <group
                  name="Light"
                  position={[-0.67, 590.39, -100.55]}
                  rotation={[1.89, 0.88, -2.05]}
                  scale={[100, 100, 100]}
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[735.89, 495.83, 692.58]}
                  rotation={[-Math.PI, 0.76, 2.68]}
                  scale={[100, 100, 100]}
                >
                  <group name="Object_8" />
                </group>
                <group name="Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Body_Material001_0"
                    geometry={nodes.Body_Material001_0.geometry}
                    material={nodes.Body_Material001_0.material}
                  />
                  <mesh
                    name="Body_Material006_0"
                    geometry={nodes.Body_Material006_0.geometry}
                    material={nodes.Body_Material006_0.material}
                  />
                  <mesh
                    name="Body_Material002_0"
                    geometry={nodes.Body_Material002_0.geometry}
                    material={nodes.Body_Material002_0.material}
                  />
                  <mesh
                    name="Body_Material003_0"
                    geometry={nodes.Body_Material003_0.geometry}
                    material={nodes.Body_Material003_0.material}
                  />
                  <mesh
                    name="Body_Material007_0"
                    geometry={nodes.Body_Material007_0.geometry}
                    material={nodes.Body_Material007_0.material}
                  />
                  <mesh
                    name="Body_Material008_0"
                    geometry={nodes.Body_Material008_0.geometry}
                    material={materials["Material.008"]}
                  />
                  <mesh
                    name="Body_Material005_0"
                    geometry={nodes.Body_Material005_0.geometry}
                    material={nodes.Body_Material005_0.material}
                  />
                </group>
                <group
                  name="Rearights"
                  position={[-0.96, 0, 0]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                  scale={22.59}
                >
                  <mesh
                    name="Rearights_Material003_0"
                    geometry={nodes.Rearights_Material003_0.geometry}
                    material={nodes.Rearights_Material003_0.material}
                  />
                  <mesh
                    name="Rearights_Material004_0"
                    geometry={nodes.Rearights_Material004_0.geometry}
                    material={materials["Material.004"]}
                  />
                </group>
                <group
                  name="WheelR"
                  position={[-321.86, 19.97, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="WheelR_Material002_0"
                    geometry={nodes.WheelR_Material002_0.geometry}
                    material={nodes.WheelR_Material002_0.material}
                  />
                  <mesh
                    name="WheelR_Material005_0"
                    geometry={nodes.WheelR_Material005_0.geometry}
                    material={nodes.WheelR_Material005_0.material}
                  />
                </group>
                <group
                  name="Body3"
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name="Body3_Material005_0"
                    geometry={nodes.Body3_Material005_0.geometry}
                    material={nodes.Body3_Material005_0.material}
                  />
                  <mesh
                    name="Body3_Material002_0"
                    geometry={nodes.Body3_Material002_0.geometry}
                    material={nodes.Body3_Material002_0.material}
                  />
                </group>
                <group
                  name="Body5"
                  position={[0, 0, 5.75]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Body5_Material006_0"
                    geometry={nodes.Body5_Material006_0.geometry}
                    material={nodes.Body5_Material006_0.material}
                  />
                </group>
                <group
                  name="Steering"
                  position={[-279.38, 44.23, 26.29]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={7.93}
                >
                  <mesh
                    name="Steering_Material006_0"
                    geometry={nodes.Steering_Material006_0.geometry}
                    material={nodes.Steering_Material006_0.material}
                  />
                </group>
                <group
                  name="Body4"
                  position={[-273.27, 25.47, 3.5]}
                  rotation={[-1.31, 0, 0]}
                  scale={0.84}
                >
                  <mesh
                    name="Body4_Material005_0"
                    geometry={nodes.Body4_Material005_0.geometry}
                    material={nodes.Body4_Material005_0.material}
                  />
                  <mesh
                    name="Body4_Material006_0"
                    geometry={nodes.Body4_Material006_0.geometry}
                    material={nodes.Body4_Material006_0.material}
                  />
                </group>
                <group
                  name="Carseat"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={30.11}
                >
                  <mesh
                    name="Carseat_Material007_0"
                    geometry={nodes.Carseat_Material007_0.geometry}
                    material={nodes.Carseat_Material007_0.material}
                  />
                </group>
                <group name="Body2" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Body2_Material009_0"
                    geometry={nodes.Body2_Material009_0.geometry}
                    material={materials["Material.009"]}
                  />
                </group>
                <group
                  name="WheelFL"
                  position={[-321.86, 19.97, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="WheelFL_Material002_0"
                    geometry={nodes.WheelFL_Material002_0.geometry}
                    material={nodes.WheelFL_Material002_0.material}
                  />
                  <mesh
                    name="WheelFL_Material005_0"
                    geometry={nodes.WheelFL_Material005_0.geometry}
                    material={nodes.WheelFL_Material005_0.material}
                  />
                </group>
                <group
                  name="WheelFR"
                  position={[-321.86, 19.97, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="WheelFR_Material002_0"
                    geometry={nodes.WheelFR_Material002_0.geometry}
                    material={nodes.WheelFR_Material002_0.material}
                  />
                  <mesh
                    name="WheelFR_Material005_0"
                    geometry={nodes.WheelFR_Material005_0.geometry}
                    material={nodes.WheelFR_Material005_0.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </animated.group>
  );
}

useGLTF.preload("/scene.glb");
