/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scene2.gltf");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.Scene.play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="scene2gltf" scale={0.7}>
          <group name="Sketchfab_Scene" scale={0.01}>
            <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
              <group
                name="22f03ca9048a47d281d0014950cde4e0fbx"
                rotation={[Math.PI / 2, 0, 0]}
              >
                <group name="Object_2">
                  <group name="RootNode">
                    <group
                      name="DoorL"
                      position={[98.88, 54.63, 73.44]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={72.42}
                    >
                      <group
                        name="Interior_13"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                      >
                        <mesh
                          name="Interior_13_Ferrari_488Pista_2019_Modified__CSBGrille4A_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Interior_13_Ferrari_488Pista_2019_Modified__CSBGrille4A_0
                              .geometry
                          }
                          material={
                            nodes
                              .Interior_13_Ferrari_488Pista_2019_Modified__CSBGrille4A_0
                              .material
                          }
                        />
                      </group>
                      <group
                        name="Interior_15"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                      >
                        <mesh
                          name="Interior_15_Instrument_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_15_Instrument_0.geometry}
                          material={nodes.Interior_15_Instrument_0.material}
                        />
                      </group>
                      <group
                        name="WindowL"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.06}
                      >
                        <mesh
                          name="WindowL_ClearGlass_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.WindowL_ClearGlass_0.geometry}
                          material={nodes.WindowL_ClearGlass_0.material}
                        />
                      </group>
                      <group
                        name="Interior_16"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.06}
                      >
                        <mesh
                          name="Interior_16_BlackLeather_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_16_BlackLeather_0.geometry}
                          material={nodes.Interior_16_BlackLeather_0.material}
                        />
                      </group>
                      <group
                        name="Interior_"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="Interior__Black_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior__Black_0.geometry}
                          material={nodes.Interior__Black_0.material}
                        />
                      </group>
                      <group
                        name="DoorL_1"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="DoorL_CarPaint_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.DoorL_CarPaint_0.geometry}
                          material={nodes.DoorL_CarPaint_0.material}
                        />
                      </group>
                      <group
                        name="MirrorL"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="MirrorL_0130_Gainsboro_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.MirrorL_0130_Gainsboro_0.geometry}
                          material={nodes.MirrorL_0130_Gainsboro_0.material}
                        />
                      </group>
                      <group
                        name="Interior_12"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.06}
                      >
                        <mesh
                          name="Interior_12_SilverFabric_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_12_SilverFabric_0.geometry}
                          material={nodes.Interior_12_SilverFabric_0.material}
                        />
                      </group>
                      <group
                        name="Interior001"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.08}
                      >
                        <mesh
                          name="Interior001_RED_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior001_RED_0.geometry}
                          material={nodes.Interior001_RED_0.material}
                        />
                      </group>
                      <group
                        name="Interior_14"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="Interior_14_EngineBlack_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_14_EngineBlack_0.geometry}
                          material={nodes.Interior_14_EngineBlack_0.material}
                        />
                        <mesh
                          name="Interior_14_Ferrari_488Pista_2019_Modified__CSBinterior_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Interior_14_Ferrari_488Pista_2019_Modified__CSBinterior_0
                              .geometry
                          }
                          material={
                            nodes
                              .Interior_14_Ferrari_488Pista_2019_Modified__CSBinterior_0
                              .material
                          }
                        />
                      </group>
                      <group
                        name="Interior002"
                        position={[-1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.08}
                      >
                        <mesh
                          name="Interior002_RED_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior002_RED_0.geometry}
                          material={nodes.Interior002_RED_0.material}
                        />
                      </group>
                    </group>
                    <group
                      name="DoorR"
                      position={[-98.88, 54.63, 73.44]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={72.42}
                    >
                      <group
                        name="Interior_18"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                      >
                        <mesh
                          name="Interior_18_Ferrari_488Pista_2019_Modified__CSBGrille4A_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Interior_18_Ferrari_488Pista_2019_Modified__CSBGrille4A_0
                              .geometry
                          }
                          material={
                            nodes
                              .Interior_18_Ferrari_488Pista_2019_Modified__CSBGrille4A_0
                              .material
                          }
                        />
                      </group>
                      <group
                        name="Interior_20"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.06}
                      >
                        <mesh
                          name="Interior_20_BlackLeather_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_20_BlackLeather_0.geometry}
                          material={nodes.Interior_20_BlackLeather_0.material}
                        />
                      </group>
                      <group
                        name="Interior_21"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.06}
                      >
                        <mesh
                          name="Interior_21_ClearGlass_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_21_ClearGlass_0.geometry}
                          material={nodes.Interior_21_ClearGlass_0.material}
                        />
                      </group>
                      <group
                        name="Interior_22"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.06}
                      >
                        <mesh
                          name="Interior_22_BlackLeather_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_22_BlackLeather_0.geometry}
                          material={nodes.Interior_22_BlackLeather_0.material}
                        />
                      </group>
                      <group
                        name="DoorR_1"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="DoorR_CarPaint_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.DoorR_CarPaint_0.geometry}
                          material={nodes.DoorR_CarPaint_0.material}
                        />
                      </group>
                      <group
                        name="MirrorR"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="MirrorR_0130_Gainsboro_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.MirrorR_0130_Gainsboro_0.geometry}
                          material={nodes.MirrorR_0130_Gainsboro_0.material}
                        />
                      </group>
                      <group
                        name="Interior_17"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.08}
                      >
                        <mesh
                          name="Interior_17_RED_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_17_RED_0.geometry}
                          material={nodes.Interior_17_RED_0.material}
                        />
                      </group>
                      <group
                        name="Interior_19"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="Interior_19_Ferrari_488Pista_2019_Modified__CSBinterior_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Interior_19_Ferrari_488Pista_2019_Modified__CSBinterior_0
                              .geometry
                          }
                          material={
                            nodes
                              .Interior_19_Ferrari_488Pista_2019_Modified__CSBinterior_0
                              .material
                          }
                        />
                        <mesh
                          name="Interior_19_Instrument_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Interior_19_Instrument_0.geometry}
                          material={nodes.Interior_19_Instrument_0.material}
                        />
                      </group>
                      <group
                        name="BlackR"
                        position={[1.37, 1.01, -0.75]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="BlackR_Black_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.BlackR_Black_0.geometry}
                          material={nodes.BlackR_Black_0.material}
                        />
                      </group>
                    </group>
                    <group
                      name="Trunk001"
                      position={[0, 79.23, 90.58]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    >
                      <group
                        name="Hood"
                        position={[0, 0.91, -0.79]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="Hood_CarPaint_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Hood_CarPaint_0.geometry}
                          material={nodes.Hood_CarPaint_0.material}
                        />
                        <mesh
                          name="Hood_CarPaint_2_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Hood_CarPaint_2_0.geometry}
                          material={nodes.Hood_CarPaint_2_0.material}
                        />
                        <mesh
                          name="Hood_CarPaint_3_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Hood_CarPaint_3_0.geometry}
                          material={nodes.Hood_CarPaint_3_0.material}
                        />
                      </group>
                      <group
                        name="Trunk"
                        position={[0, 0.91, -0.79]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                      >
                        <mesh
                          name="Trunk_CarbonFiber_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Trunk_CarbonFiber_0.geometry}
                          material={nodes.Trunk_CarbonFiber_0.material}
                        />
                      </group>
                    </group>
                    <group
                      name="Engine"
                      position={[0, 113.45, -73.13]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    >
                      <group
                        name="Black001"
                        position={[0, -0.73, -1.13]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.18}
                      >
                        <mesh
                          name="Black001_Black_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Black001_Black_0.geometry}
                          material={nodes.Black001_Black_0.material}
                        />
                      </group>
                      <group
                        name="Grill001"
                        position={[0, -0.73, -1.13]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.13}
                      >
                        <mesh
                          name="Grill001_Grill_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Grill001_Grill_0.geometry}
                          material={nodes.Grill001_Grill_0.material}
                        />
                      </group>
                      <group
                        name="EngineGlass001"
                        position={[0, -0.73, -1.13]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.04}
                      >
                        <mesh
                          name="EngineGlass001_ClearGlass_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.EngineGlass001_ClearGlass_0.geometry}
                          material={nodes.EngineGlass001_ClearGlass_0.material}
                        />
                      </group>
                      <group
                        name="Black003"
                        position={[0, -0.73, -1.13]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.18}
                      >
                        <mesh
                          name="Black003_Black_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Black003_Black_0.geometry}
                          material={nodes.Black003_Black_0.material}
                        />
                      </group>
                    </group>
                    <group
                      name="Empty"
                      position={[0, 0, 1.64]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={[167, 218, 144]}
                    />
                    <group name="TailLights" scale={7.16}>
                      <mesh
                        name="TailLights_RedGlass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.TailLights_RedGlass_0.geometry}
                        material={materials.RedGlass}
                      />
                    </group>
                    <group name="WindShield" scale={17.94}>
                      <mesh
                        name="WindShield_ClearGlass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.WindShield_ClearGlass_0.geometry}
                        material={nodes.WindShield_ClearGlass_0.material}
                      />
                    </group>
                    <group name="OrangeGlass" scale={7.95}>
                      <mesh
                        name="OrangeGlass_OrangeGlass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.OrangeGlass_OrangeGlass_0.geometry}
                        material={materials.OrangeGlass}
                      />
                    </group>
                    <group name="Interior_1" scale={3.07}>
                      <mesh
                        name="Interior_1_Black_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_1_Black_0.geometry}
                        material={nodes.Interior_1_Black_0.material}
                      />
                    </group>
                    <group name="Body" scale={18.89}>
                      <mesh
                        name="Body_CarPaint_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_CarPaint_0.geometry}
                        material={nodes.Body_CarPaint_0.material}
                      />
                      <mesh
                        name="Body_CarPaint_2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_CarPaint_2_0.geometry}
                        material={nodes.Body_CarPaint_2_0.material}
                      />
                      <mesh
                        name="Body_CarPaint_3_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_CarPaint_3_0.geometry}
                        material={nodes.Body_CarPaint_3_0.material}
                      />
                    </group>
                    <group name="Lights" scale={17.94}>
                      <mesh
                        name="Lights_Ferrari_488Pista_2019_Modified__CSBLights_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .Lights_Ferrari_488Pista_2019_Modified__CSBLights_0
                            .geometry
                        }
                        material={
                          materials.Ferrari_488Pista_2019_Modified__CSBLights
                        }
                      />
                    </group>
                    <group name="Interior_3" scale={10.42}>
                      <mesh
                        name="Interior_3_Instrument_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_3_Instrument_0.geometry}
                        material={nodes.Interior_3_Instrument_0.material}
                      />
                    </group>
                    <group name="Interior_5" scale={6.96}>
                      <mesh
                        name="Interior_5_BlackLeather_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_5_BlackLeather_0.geometry}
                        material={nodes.Interior_5_BlackLeather_0.material}
                      />
                    </group>
                    <group name="Interior" scale={5.45}>
                      <mesh
                        name="Interior_RED_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_RED_0.geometry}
                        material={nodes.Interior_RED_0.material}
                      />
                    </group>
                    <group name="Radiator" scale={6.48}>
                      <mesh
                        name="Radiator_Silver_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Radiator_Silver_0.geometry}
                        material={materials.Silver}
                      />
                    </group>
                    <group name="Interior_6" scale={4.27}>
                      <mesh
                        name="Interior_6_SilverFabric_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_6_SilverFabric_0.geometry}
                        material={nodes.Interior_6_SilverFabric_0.material}
                      />
                    </group>
                    <group name="Grill" scale={12.9}>
                      <mesh
                        name="Grill_Grill_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Grill_Grill_0.geometry}
                        material={nodes.Grill_Grill_0.material}
                      />
                    </group>
                    <group name="Silver" scale={1.79}>
                      <mesh
                        name="Silver_Silver001_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Silver_Silver001_0.geometry}
                        material={materials["Silver.001"]}
                      />
                    </group>
                    <group name="Engine_2" scale={5.46}>
                      <mesh
                        name="Engine_2_EngineBlack_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Engine_2_EngineBlack_0.geometry}
                        material={nodes.Engine_2_EngineBlack_0.material}
                      />
                      <mesh
                        name="Engine_2_EngineGray_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Engine_2_EngineGray_0.geometry}
                        material={materials.EngineGray}
                      />
                      <mesh
                        name="Engine_2_EngineDarkGray_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Engine_2_EngineDarkGray_0.geometry}
                        material={materials.EngineDarkGray}
                      />
                    </group>
                    <group name="Black" scale={18.36}>
                      <mesh
                        name="Black_Black_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Black_Black_0.geometry}
                        material={nodes.Black_Black_0.material}
                      />
                    </group>
                    <group name="CarbonFiber" scale={18.87}>
                      <mesh
                        name="CarbonFiber_CarbonFiber_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.CarbonFiber_CarbonFiber_0.geometry}
                        material={nodes.CarbonFiber_CarbonFiber_0.material}
                      />
                    </group>
                    <group name="Badge" scale={18.36}>
                      <mesh
                        name="Badge_Badge_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Badge_Badge_0.geometry}
                        material={nodes.Badge_Badge_0.material}
                      />
                    </group>
                    <group name="Windowbk" scale={3.53}>
                      <mesh
                        name="Windowbk_ClearGlass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Windowbk_ClearGlass_0.geometry}
                        material={nodes.Windowbk_ClearGlass_0.material}
                      />
                    </group>
                    <group name="Spoiler" scale={5.98}>
                      <mesh
                        name="Spoiler_CarPaint_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Spoiler_CarPaint_0.geometry}
                        material={nodes.Spoiler_CarPaint_0.material}
                      />
                      <mesh
                        name="Spoiler_CarPaint_3_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Spoiler_CarPaint_3_0.geometry}
                        material={nodes.Spoiler_CarPaint_3_0.material}
                      />
                      <mesh
                        name="Spoiler_CarPaint_2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Spoiler_CarPaint_2_0.geometry}
                        material={nodes.Spoiler_CarPaint_2_0.material}
                      />
                    </group>
                    <group
                      name="Interior_11"
                      position={[-53.91, 92.65, 34.13]}
                      rotation={[0.42, 0.32, -1.27]}
                      scale={[1.15, 1.15, 1.15]}
                    >
                      <mesh
                        name="Interior_11_Instrument_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_11_Instrument_0.geometry}
                        material={nodes.Interior_11_Instrument_0.material}
                      />
                    </group>
                    <group
                      name="Interior_10"
                      position={[-53.91, 92.65, 34.13]}
                      rotation={[0.42, 0.32, -1.27]}
                      scale={[0.21, 0.21, 0.21]}
                    >
                      <mesh
                        name="Interior_10_Badge_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_10_Badge_0.geometry}
                        material={nodes.Interior_10_Badge_0.material}
                      />
                    </group>
                    <group name="Chrome" scale={17.94}>
                      <mesh
                        name="Chrome_Chrome_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Chrome_Chrome_0.geometry}
                        material={materials.Chrome}
                      />
                    </group>
                    <group name="Emissive" scale={17.94}>
                      <mesh
                        name="Emissive_HeadLight_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Emissive_HeadLight_0.geometry}
                        material={materials.HeadLight}
                      />
                      <mesh
                        name="Emissive_TailLight_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Emissive_TailLight_0.geometry}
                        material={materials.TailLight}
                      />
                    </group>
                    <group name="Glass" scale={17.94}>
                      <mesh
                        name="Glass_Glass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Glass_Glass_0.geometry}
                        material={materials.Glass}
                      />
                    </group>
                    <group name="TailLight" scale={6.87}>
                      <mesh
                        name="TailLight_ClearGlass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.TailLight_ClearGlass_0.geometry}
                        material={nodes.TailLight_ClearGlass_0.material}
                      />
                    </group>
                    <group name="Interior_8" scale={18.36}>
                      <mesh
                        name="Interior_8_0130_Gainsboro_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_8_0130_Gainsboro_0.geometry}
                        material={nodes.Interior_8_0130_Gainsboro_0.material}
                      />
                    </group>
                    <group name="Interior_7" scale={4.27}>
                      <mesh
                        name="Interior_7_Ferrari_488Pista_2019_Modified__CSBGrille5A001_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .Interior_7_Ferrari_488Pista_2019_Modified__CSBGrille5A001_0
                            .geometry
                        }
                        material={
                          materials[
                            "Ferrari_488Pista_2019_Modified__CSBGrille5A.001"
                          ]
                        }
                      />
                    </group>
                    <group
                      name="wheelbrakeFtL"
                      position={[96.83, 34.76, 119.57]}
                      rotation={[0.21, 0, -0.02]}
                      scale={1.35}
                    >
                      <mesh
                        name="wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeFtL_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="wheelFtL"
                      position={[96.83, 34.76, 119.57]}
                      rotation={[0, 0, -0.02]}
                      scale={2.79}
                    >
                      <mesh
                        name="wheelFtL_Rims1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelFtL_Rims1_0.geometry}
                        material={nodes.wheelFtL_Rims1_0.material}
                      />
                      <mesh
                        name="wheelFtL_Badge_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelFtL_Badge_0.geometry}
                        material={nodes.wheelFtL_Badge_0.material}
                      />
                      <mesh
                        name="wheelFtL_Material003_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelFtL_Material003_0.geometry}
                        material={nodes.wheelFtL_Material003_0.material}
                      />
                      <mesh
                        name="wheelFtL_Ferrari_488Pista_2019_Modified__CSBWheel1A_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelFtL_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelFtL_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="wheelbrakeBkL"
                      position={[97.42, 34.96, -156.5]}
                      rotation={[2.68, 0, -0.02]}
                      scale={1.36}
                    >
                      <mesh
                        name="wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeBkL_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="wheelbrakeFtR"
                      position={[-96.83, 34.76, 119.57]}
                      rotation={[0.41, 0, 3.12]}
                      scale={[1.35, 1.35, 1.35]}
                    >
                      <mesh
                        name="wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrakeFtR_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="wheelFtR"
                      position={[-96.83, 34.76, 119.57]}
                      rotation={[Math.PI, 0, 3.12]}
                      scale={2.79}
                    >
                      <mesh
                        name="wheelFtR_Rims1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelFtR_Rims1_0.geometry}
                        material={nodes.wheelFtR_Rims1_0.material}
                      />
                      <mesh
                        name="wheelFtR_Badge_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelFtR_Badge_0.geometry}
                        material={nodes.wheelFtR_Badge_0.material}
                      />
                      <mesh
                        name="wheelFtR_Material003_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelFtR_Material003_0.geometry}
                        material={nodes.wheelFtR_Material003_0.material}
                      />
                      <mesh
                        name="wheelFtR_Ferrari_488Pista_2019_Modified__CSBWheel1A_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelFtR_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelFtR_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="wheelbrkaeBkR"
                      position={[-97.53, 34.96, -156.5]}
                      rotation={[2.86, 0, 3.12]}
                      scale={[1.36, 1.36, 1.36]}
                    >
                      <mesh
                        name="wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBPaintCaliper_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBColouredMtl_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelbrkaeBkR_Ferrari_488Pista_2019_Modified__CSBCalliperBadgeBMtl_0
                            .material
                        }
                      />
                    </group>
                    <group name="SuperDark" scale={11.28}>
                      <mesh
                        name="SuperDark_SuperDark_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.SuperDark_SuperDark_0.geometry}
                        material={materials.SuperDark}
                      />
                    </group>
                    <group name="Interior_2" scale={11.28}>
                      <mesh
                        name="Interior_2_Speedomter_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_2_Speedomter_0.geometry}
                        material={materials.Speedomter}
                      />
                    </group>
                    <group name="Interior_4" scale={10.42}>
                      <mesh
                        name="Interior_4_Instrument_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_4_Instrument_0.geometry}
                        material={nodes.Interior_4_Instrument_0.material}
                      />
                    </group>
                    <group name="Interior_9" scale={18.36}>
                      <mesh
                        name="Interior_9_Black001_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Interior_9_Black001_0.geometry}
                        material={materials["Black.001"]}
                      />
                    </group>
                    <group name="HeadLightsGlass" scale={17.94}>
                      <mesh
                        name="HeadLightsGlass_ClearGlass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.HeadLightsGlass_ClearGlass_0.geometry}
                        material={nodes.HeadLightsGlass_ClearGlass_0.material}
                      />
                    </group>
                    <group
                      name="wheelBkR"
                      position={[-97.31, 34.96, -156.5]}
                      rotation={[Math.PI, 0, 3.12]}
                      scale={[2.81, 2.81, 2.81]}
                    >
                      <mesh
                        name="wheelBkR_Ferrari_488Pista_2019_Modified__CSBWheel2A_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelBkR_Ferrari_488Pista_2019_Modified__CSBWheel2A_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelBkR_Ferrari_488Pista_2019_Modified__CSBWheel2A_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelBkR_Rims1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelBkR_Rims1_0.geometry}
                        material={nodes.wheelBkR_Rims1_0.material}
                      />
                      <mesh
                        name="wheelBkR_Badge_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelBkR_Badge_0.geometry}
                        material={nodes.wheelBkR_Badge_0.material}
                      />
                      <mesh
                        name="wheelBkR_Material003_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelBkR_Material003_0.geometry}
                        material={nodes.wheelBkR_Material003_0.material}
                      />
                      <mesh
                        name="wheelBkR_Ferrari_488Pista_2019_Modified__CSBWheel1A_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelBkR_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelBkR_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="wheelBkL"
                      position={[97.52, 34.96, -156.5]}
                      rotation={[0, 0, -0.02]}
                      scale={[2.81, 2.81, 2.81]}
                    >
                      <mesh
                        name="wheelBkL_Ferrari_488Pista_2019_Modified__CSBWheel2A_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelBkL_Ferrari_488Pista_2019_Modified__CSBWheel2A_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelBkL_Ferrari_488Pista_2019_Modified__CSBWheel2A_0
                            .material
                        }
                      />
                      <mesh
                        name="wheelBkL_Rims1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelBkL_Rims1_0.geometry}
                        material={nodes.wheelBkL_Rims1_0.material}
                      />
                      <mesh
                        name="wheelBkL_Badge_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelBkL_Badge_0.geometry}
                        material={nodes.wheelBkL_Badge_0.material}
                      />
                      <mesh
                        name="wheelBkL_Material003_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.wheelBkL_Material003_0.geometry}
                        material={nodes.wheelBkL_Material003_0.material}
                      />
                      <mesh
                        name="wheelBkL_Ferrari_488Pista_2019_Modified__CSBWheel1A_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .wheelBkL_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .geometry
                        }
                        material={
                          nodes
                            .wheelBkL_Ferrari_488Pista_2019_Modified__CSBWheel1A_0
                            .material
                        }
                      />
                    </group>
                    <group
                      name="Cube"
                      position={[0, 45.01, -232.51]}
                      rotation={[-1.68, 0, 0]}
                      scale={[23.67, 0.82, 7.59]}
                    >
                      <mesh
                        name="Cube_Material012_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_Material012_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene2.gltf");